input {
  kafka {
    bootstrap_servers => "localhost:9092" # <- Change this if kafka server is different
    topics => ["entity-count"] # <- Change this to TOPIC2 if needed
    codec => "json"
    group_id => "logstash-entity-count"
  }
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"] # <- Change this if elasticsearch server is different
    index => "entity-counts-%{+YYYY.MM.dd}"
  }
}